(()=>{
'use strict';
function goTopViaAd(){try{if(window.platform_sdk&&typeof window.platform_sdk.back_to_top==='function'){window.platform_sdk.back_to_top();return true;}}catch(e){}return false;}
const SIZE=8,EMPTY=0,BLACK=1,WHITE=-1,DIRS=[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]];
const $board=document.getElementById('board'),$starter=document.getElementById('starter'),$difficulty=document.getElementById('difficulty'),$newGame=document.getElementById('newGame'),$turn=document.getElementById('turnLabel'),$count=document.getElementById('countLabel'),$msg=document.getElementById('msg'),$startBtn=document.getElementById('btnStart'),$btnToTop=document.getElementById('btnToTop'),$toggleHints=document.getElementById('toggleHints'),$screenConfig=document.getElementById('screenTop'),$screenGame=document.getElementById('screenGame');
function showScreen(which){if(which==='config'){$screenConfig.classList.remove('hidden');$screenGame.classList.add('hidden');}else{$screenConfig.classList.add('hidden');$screenGame.classList.remove('hidden');}}
let board,turn,HUMAN,CPU,busy=false,finished=false,showHints=true,gameStarted=false;
const inside=(r,c)=>r>=0&&r<SIZE&&c>=0&&c<SIZE,clone=b=>b.map(row=>row.slice());
function initBoard(){const b=Array.from({length:SIZE},()=>Array(SIZE).fill(EMPTY));b[3][3]=WHITE;b[3][4]=BLACK;b[4][3]=BLACK;b[4][4]=WHITE;return b;}
function flips(b,r,c,p){if(b[r][c]!==EMPTY)return[];const opp=-p,out=[];for(const[dr,dc]of DIRS){let rr=r+dr,cc=c+dc,tmp=[];while(inside(rr,cc)&&b[rr][cc]===opp){tmp.push([rr,cc]);rr+=dr;cc+=dc;}if(tmp.length&&inside(rr,cc)&&b[rr][cc]===p)out.push(...tmp);}return out;}
function legalMoves(b,p){const ms=[];for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++){const f=flips(b,r,c,p);if(f.length)ms.push({r,c,f});}return ms;}
function applyMove(b,m,p){const nb=clone(b);nb[m.r][m.c]=p;for(const[rr,cc]of m.f)nb[rr][cc]=p;return nb;}
function countDiscs(b){let black=0,white=0;for(const row of b)for(const v of row){if(v===BLACK)black++;else if(v===WHITE)white++;}return{black,white};}
function isGameOver(b){return legalMoves(b,BLACK).length===0&&legalMoves(b,WHITE).length===0;}
function evalBoard(b,maxColor){const{black,white}=countDiscs(b);let score=maxColor===BLACK?black-white:white-black;for(const[r,c]of[[0,0],[0,7],[7,0],[7,7]]){if(b[r][c]===maxColor)score+=3;else if(b[r][c]===-maxColor)score-=3;}return score;}
function minimax(b,player,depth,alpha,beta,maxColor){if(depth<=0||isGameOver(b))return evalBoard(b,maxColor);const moves=legalMoves(b,player);if(!moves.length)return minimax(b,-player,depth-1,alpha,beta,maxColor);if(player===maxColor){let best=-Infinity;for(const m of moves){best=Math.max(best,minimax(applyMove(b,m,player),-player,depth-1,alpha,beta,maxColor));alpha=Math.max(alpha,best);if(beta<=alpha)break;}return best;}let best=Infinity;for(const m of moves){best=Math.min(best,minimax(applyMove(b,m,player),-player,depth-1,alpha,beta,maxColor));beta=Math.min(beta,best);if(beta<=alpha)break;}return best;}
function chooseCpuMove(b,player,depth){const moves=legalMoves(b,player);if(!moves.length)return null;let bestMove=moves[0],best=-Infinity;for(const m of moves){const v=minimax(applyMove(b,m,player),-player,Math.max(0,depth-1),-Infinity,Infinity,player)+(((m.r===0||m.r===7)&&(m.c===0||m.c===7))?.25:0);if(v>best){best=v;bestMove=m;}}return bestMove;}
const setMsg=t=>$msg.textContent=t,randDelay=()=>220+Math.floor(Math.random()*180);
function render(){const moves=legalMoves(board,turn),hintSet=new Set(moves.map(m=>m.r+','+m.c));$board.innerHTML='';for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++){const cell=document.createElement('button');cell.type='button';cell.className='cell';cell.dataset.r=String(r);cell.dataset.c=String(c);cell.setAttribute('role','gridcell');cell.setAttribute('aria-label',`行${r+1} 列${c+1}`);const v=board[r][c];if(v!==EMPTY){const d=document.createElement('span');d.className='disc '+(v===BLACK?'black':'white');cell.appendChild(d);}else if(showHints&&!busy&&!finished&&turn===HUMAN&&hintSet.has(r+','+c))cell.classList.add('hint');cell.addEventListener('click',()=>onCellClick(r,c));$board.appendChild(cell);}const{black,white}=countDiscs(board);$count.textContent=`黒 ${black} / 白 ${white}`;$turn.textContent=`手番: ${turn===BLACK?'黒':'白'}${turn===CPU?'（CPU）':'（あなた）'}`;if(finished)return;if(isGameOver(board)){finishGame();return;}if(!moves.length){setMsg('置ける場所がないためパスします');busy=true;setTimeout(()=>{busy=false;turn=-turn;setMsg('');tick();},300);return;}setMsg(turn===HUMAN?'あなたの手番です':'CPUが考えています…');}
function onCellClick(r,c){if(busy||finished||turn!==HUMAN)return;const f=flips(board,r,c,turn);if(!f.length)return;board=applyMove(board,{r,c,f},turn);turn=-turn;tick();}
function tick(){render();if(finished||busy||turn!==CPU)return;const move=chooseCpuMove(board,CPU,parseInt($difficulty.value,10)||3);if(!move){render();return;}busy=true;setMsg('CPUが考えています…');setTimeout(()=>{board=applyMove(board,move,CPU);turn=-turn;busy=false;tick();},randDelay());}
function finishGame(){if(finished)return;finished=true;const{black,white}=countDiscs(board),humanCount=HUMAN===BLACK?black:white,cpuCount=CPU===BLACK?black:white,result=humanCount>cpuCount?'win':humanCount<cpuCount?'lose':'draw';setMsg(`終了: ${result==='win'?'勝ち':result==='lose'?'負け':'引き分け'}（あなた ${humanCount} / CPU ${cpuCount}）`);try{window.platform_sdk?.finish?.(humanCount,{result,human_color:HUMAN===BLACK?'black':'white',cpu_color:CPU===BLACK?'black':'white',black,white,diff:humanCount-cpuCount,level:parseInt($difficulty.value,10)||3});}catch(e){}}
function startNewGame(){finished=false;busy=false;board=initBoard();if($starter.value==='cpu'){CPU=BLACK;HUMAN=WHITE;turn=CPU;}else{HUMAN=BLACK;CPU=WHITE;turn=HUMAN;}setMsg('');tick();}
$newGame?.addEventListener('click',startNewGame);$starter.addEventListener('change',()=>{if(gameStarted)startNewGame();});$difficulty.addEventListener('change',()=>{if(gameStarted&&!finished)tick();});showScreen('config');$toggleHints?.addEventListener('click',()=>{showHints=!showHints;$toggleHints.classList.toggle('on',showHints);$toggleHints.textContent=showHints?'候補: ON':'候補: OFF';if(gameStarted)render();});$toggleHints?.classList.toggle('on',showHints);$startBtn?.addEventListener('click',()=>{gameStarted=true;showScreen('game');startNewGame();});$btnToTop?.addEventListener('click',()=>{if(!goTopViaAd())showScreen('config');});
})();